# Generated by Django 4.1.6 on 2023-03-27 00:58

from django.db import migrations


def populate_db(apps, schema_editor):
    ConversionFactor = apps.get_model('unitconv', 'ConversionFactor')

    T = ConversionFactor(name="T", to_pounds=2000)
    T.save()
    g = ConversionFactor(name="g", to_pounds=.002204585)
    g.save()
    t_oz = ConversionFactor(name="t_oz", to_pounds=.068572996)
    t_oz.save()
    kg = ConversionFactor(name="kg", to_pounds=2.205)
    kg.save()
    lb = ConversionFactor(name="lb", to_pounds=1)
    lb.save()
    oz = ConversionFactor(name="oz", to_pounds=.0625)
    oz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
